# Generated by Django 2.1.7 on 2019-02-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0003_auto_20190213_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
